# Generated by Django 4.2.2 on 2023-07-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_image', models.ImageField(upload_to='static/category_images/')),
                ('category_slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(upload_to='static/products_images/'),
        ),
    ]
