# Generated by Django 4.2.2 on 2023-07-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0003_rename_cart_carts_rename_category_categorys_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorys',
            new_name='Categories',
        ),
    ]
