# Generated by Django 4.2.2 on 2023-07-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0005_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='product_qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
