# Generated by Django 4.2.2 on 2023-07-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0007_carts_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='product_price',
            new_name='cart_product_price',
        ),
        migrations.RenameField(
            model_name='carts',
            old_name='product_qty',
            new_name='cart_product_qty',
        ),
    ]
