# Generated by Django 4.2.2 on 2023-07-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0008_rename_product_price_carts_cart_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='cart_product_price',
        ),
    ]
