# Generated by Django 4.2.2 on 2023-08-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0009_remove_carts_cart_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='cart_product_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.CharField(choices=[('smartphone', 'smartphone'), ('laptop', 'laptop'), ('smartwatch', 'smartwatch')], max_length=10),
        ),
    ]
