# Generated by Django 4.2.2 on 2023-08-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0010_alter_carts_cart_product_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.CharField(choices=[('smartwatch', 'smartwatch')], max_length=10),
        ),
    ]
