# Generated by Django 4.2.2 on 2023-08-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0011_alter_products_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.CharField(choices=[], max_length=10),
        ),
    ]
